### ISSUE TITLE
CM File - No Description Entries in File

### ISSUE THREAD

**Issue by AntonPetrov** [Rfam/rfam-production#1]
The current version of the Covariance Models file does not contain description entries ("DESC") for all CMs (ftp://ftp.ebi.ac.uk/pub/databases/Rfam/CURRENT/Rfam.cm.gz)

For family descriptions users need to parse the family table database dump:
ftp://ftp.ebi.ac.uk/pub/databases/Rfam/CURRENT/database_files/family.txt.gz

**Comment by kalvari** [comment]
Looked back into releases 9.0, 11.0 and 12.0  and there are no DESC lines in the CMs of any of the releases.
