### ISSUE TITLE
Add update_rnacentral_descriptions to nextflow

### ISSUE THREAD

**Issue by AntonPetrov** [Rfam/rfam-production#116]
There is a new script [update_rnacentral_description.py](https://github.com/Rfam/rfam-production/blob/master/scripts/release/update_rnacentral_description.py) that needs to be run every release to make sure that all RNAcentral descriptions are up to date in the `rfamseq` table. 

I added a new step to the release checklist #103. 

@emmaco Emma,  could you please add the script to the main release pipeline in nextflow? Thanks in advance!

**Comment by emmaco** [comment]
As part of release 14.8, this now runs as a process in the prepare_rfam_live.nf pipeline.
