### ISSUE TITLE
Download sequences using the NCBI Datasets CLI tool

### ISSUE THREAD

**Issue by AntonPetrov** [Rfam/rfam-production#118]
NCBI provides a [new CLI tool](https://www.ncbi.nlm.nih.gov/datasets/docs/v1/how-tos/genomes/download-genome/) for downloading genomes.

For example, run the following command:

```
datasets download genome accession GCA_000005845.2 --filename GCA_000005845.zip  --exclude-gff3 --exclude-protein --exclude-rna --exclude-genomic-cds  
unzip -d GCA_000005845 GCA_000005845.zip 
```

to get a FASTA file ending in `_genomic.fna` that will be used to build Rfamseq.

**Comment by blakesweeney** [comment]
This is no longer needed. It turns out we cannot use that binary. Some of the
genomes in the Uniprot genomes are not found by the tool (old versions, etc), so
we cannot use it. Instead we have developed a tool to download from NCBI
ourselves.
