### ISSUE TITLE
Rfamseq fixes

### ISSUE THREAD

**Issue by AntonPetrov** [Rfam/rfam-production#16]
- [x] yeast mitochondrion accession KP263414 has not been downloaded [UP000002311](http://www.uniprot.org/proteomes/UP000002311)
- [x] frog genome (_X. tropicalis_) is an order of magnitude shorter

**Comment by kalvari** [comment]
yeast mitochondrion accession is not available from ENA http://www.ebi.ac.uk/ena/data/view/GCA_000146045.1&display=xml
ftp://ftp.ebi.ac.uk/pub/databases/ena/assembly/GCA_000/GCA_000146/GCA_000146045.1_sequence_report.txt

Need to decide whether to fetch accessions from Uniprot or ENA or Both

**Comment by AntonPetrov** [comment]
All issues have been resolved.
