### ISSUE TITLE
Build ~200 families based on Zasha's alignments

### ISSUE THREAD

**Issue by AntonPetrov** [Rfam/rfam-production#18]
- [ ] automate rf-searching and rf-replacing
- [ ] automate DESC file creation
- [ ] explore using EMG data or Zasha's sequence dataset

**Comment by ppgardne** [comment]
HAHA. I remember this problem. It's a good problem to have. 

Maybe create Zashafam...

**Comment by AntonPetrov** [comment]
Done.
