### ISSUE TITLE
Creating pipeline for scanning RNAcentral sequences with Rfam models

### ISSUE THREAD

**Issue by blakesweeney** [Rfam/rfam-production#24]
As part of the new integration between Rfam and RNAcentral we need to run all Rfam models against all RNAcentral sequences before each release. We then need to perform clan competition on the results to have clean search results. This can be broken into two tasks, scanning all sequences with any new models/clans and scanning all new sequences with all models. It is easy enough on the RNAcentral side to fetch all new sequences, though I haven't automated it yet. Right now we can do this but it is a bit of manual work we need to eliminate.

**Comment by kalvari** [comment]
Will be made available with the new point release `14.1`

**Comment by AntonPetrov** [comment]
Done.
