### ISSUE TITLE
Fix motif page RM00023

### ISSUE THREAD

**Issue by kalvari** [Rfam/rfam-production#34]
http://rfam.org/motif/RM00023 - has no wikipedia annotation?  Looks messy (Rob Finn)
This seems to be a general issue. More motifs have no wiki annotations. 

Other examples:
RM00014
RM00006
RM00021

Probably a plugin issue.

**Comment by ppgardne** [comment]
RM00022, RM00023 & RM00025 should point to the https://en.wikipedia.org/wiki/Intrinsic_termination article. 

RM00014 should point to https://en.wikipedia.org/w/index.php?title=Shine-Dalgarno_sequence

RM00006 should point to https://en.wikipedia.org/w/index.php?title=Tetraloop

RM00021 should point to https://en.wikipedia.org/w/index.php?title=Internal_loop

**Comment by JoannaArgasinska** [comment]
We need to find out how to check out motifs

**Comment by AntonPetrov** [comment]
It turns out this was related to LWP proxy settings so that the web code could not retrieve wikipedia content. No changes in wiki links were necessary. Thanks everyone!
